# sample config file

git:
   access_token: "xxxxxx"
   username: "swayaam"
   email: "swayamraina@gmail.com"
   private: false

refresh:
   interval: 20
   unit: m

sync:
   - repo: "dc"
     merge: false
     locations:
        - /comic-con/flash/villan/
        - /comic-con/batman/villan/
   - repo: "marvel"
     merge: true
     locations:
        - /comic-con/iron-man/villan/
        - /comic-con/cap-america/villan/
